on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: GMZwinge/bug-dependabot-action-repo@v1.0.1
      - uses: GMZwinge/bug-dependabot-action-repo@v1.0.1
      - uses: GMZwinge/bug-dependabot-action-repo@v1.0.2
